const shirts_data = [
    {
        id:1,
        image:"/images/shirt1.jpg",
        name: "Nkunim",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "short sleeves",
        price: "GHS170",
    },
    {
        id:2,
        image:"/images/long1.jpg",
        name: "Ankos",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "long sleeves",
        price: "GHS270",
    },
    {
        id:3,
        image:"/images/shirt2.jpg",
        name: "Kente",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "short sleeves",
        price: "GHS200",
    },
    {
        id:4,
        image:"/images/long2.jpg",
        name: "HiTarget",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "long sleeves",
        price: "GHS370",
    },
    {
        id:5,
        image:"/images/shirt4.jpg",
        name: "Tubhani",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "short sleeves",
        price: "GHS150",
    },
    {
        id:6,
        image:"/images/long3.jpg",
        name: "Sankofa",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "long sleeves",
        price: "GHS250",
    },
    {
        id:7,
        image:"/images/shirt7.jpg",
        name: "Lapel",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "short sleeves",
        price: "GHS180",
    },
    {
        id:8,
        image:"/images/shirt8.jpg",
        name: "Toney",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "short sleeves",
        price: "GHS170",
    },
    {
        id:9,
        image:"/images/long4.jpg",
        name: "KOfi",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "long sleeves",
        price: "GHS170",
    },
    {
        id:10,
        image:"/images/long5.jpg",
        name: "Bretuo",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "long sleeves",
        price: "GHS170",
    },
    {
        id:11,
        image:"/images/kaf1.jpg",
        name: "Nsunyh",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS300",
    },
    {
        id:12,
        image:"/images/shorts1.jpg",
        name: "Nika",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "shorts",
        price: "GHS150",
    },
    {
        id:13,
        image:"/images/tra1.jpg",
        name: "akyekyede",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "trousers",
        price: "GHS170",
    },
    {
        id:14,
        image:"/images/kaf2.jpg",
        name: "Buumu",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS390",
    },
    {
        id:15,
        image:"/images/tra2.jpg",
        name: "yene",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "trousers",
        price: "GHS200",
    },
    {
        id:16,
        image:"/images/kaf3.jpg",
        name: "Abotre",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS400",
    },
    {
        id:17,
        image:"/images/kaf4.jpg",
        name: "Nimo",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS450",
    },
    {
        id:18,
        image:"/images/tra3.jpg",
        name: "Osse",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "trousers",
        price: "GHS170",
    },
    {
        id:19,
        image:"/images/tra4.jpg",
        name: "Bretuo",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "trousers",
        price: "GHS160",
    },
    {
        id:20,
        image:"/images/kaf5.jpg",
        name: "Vicoire",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS800",
    },
    {
        id:21,
        image:"/images/kaf6.jpg",
        name: "Yellu",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS450",
    },
    {
        id:22,
        image:"/images/kaf7.jpg",
        name: "Ntro",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "kaftan",
        price: "GHS500",
    },
    {
        id:23,
        image:"/images/kaf8.jpg",
        name: "Nsuo",
        sizes_available: "s,m,l,xl,xxl,xxxl",
        category: "Kaftan",
        price: "GHS570",
    },
    
]

export default shirts_data;